[build-system]
requires = ["uv-build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[project]
name = "dublib"
version = "0.30.0"
description = "Коллекция полезных модулей от DUB1401."
authors = [
	{name = "DUB1401", email = "vlad.milosta@outlook.com"}
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.12"
dependencies = [
	"curl_cffi>=0.16.0",
	"dateparser",
	"ua-generator>=2.1.3",
	"httpx",
	"httpx[http2]",
	"more-itertools",
	"orjson",
	"prettytable",
	"requests",
	"pathvalidate",
	"PyJWT",
	"pyyaml",
	"pydantic",
	"validators",
	"watchfiles",
	"gnureadline>=8.3.3; sys_platform == \"linux\"",
	"pyreadline3; sys_platform == \"win32\""
]
classifiers = [
	"Development Status :: 4 - Beta",
	"Natural Language :: Russian",
	"Operating System :: OS Independent",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: 3.14"
]

[project.optional-dependencies]
telebot = [
	"APScheduler",
	"pyTelegramBotAPI"
]
dev = [
	"mypy",
	"myst_parser",
	"pytest",
	"ruff",
	"Sphinx",
	"sphinx-rtd-theme"
]

[project.urls]
Documentation = "https://github.com/DUB1401/dublib/tree/main/docs"
"Source Code" = "https://github.com/DUB1401/dublib"
"Bug Tracker" = "https://github.com/DUB1401/dublib/issues"
Changelog = "https://github.com/DUB1401/dublib/releases"

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
non_interactive = true
follow_imports = "silent"
files = ["src"]

[tool.ruff]
include = ["src/*", "tests/*"]

[tool.ruff.lint]
select = ["A", "ARG", "C", "E", "F", "I"]
extend-select = ["N"] 
ignore = ["E701", "E501"]

[tool.ruff.lint.per-file-ignores]
"!dublib/functions/**.py" = ["N"]
"tests/*" = ["S101"]

[tool.ruff.lint.isort]
lines-after-imports = 1
