name: Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "src/dublib/Engine/Bus.py"
      - "src/dublib/Functions/Data.py"
      - "src/dublib/Polyglot/**"
      - "tests/**"
  pull_request:
    paths:
      - "src/dublib/Engine/Bus.py"
      - "src/dublib/Functions/Data.py"
      - "src/dublib/Polyglot/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv pip install --system .[dev]

      - name: Run tests
        run: pytest -v
